server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka

spring:
  application:
     name: movie-web
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.cn.share.movie.web.dao
